### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by SaviorZeus** [shchmue/Lockpick#10]
EveryTime i open homebrew and click on Lockpick to dump my keys it crashes all the time idk why i got it to work once on 6.2 after that it stoped working period it doest matter which firmware i was on which cfw i was using it crashes everytime please help 

error code :2168-0002(0x4a8)
Title :0100000000001D
Firmware:7.0.1 (Atmosphere 0.8.4- master-37161c5d)

**Comment by shchmue** [comment]
that sounds like a problem with your SD files. make sure Lockpick.nro is in the /switch folder on SD, and that your hbmenu and hbloader files are up to date. does other Homebrew work?

**Comment by CVFireDragon** [comment]
@SaviorZeus the problem is that 7.0 / 7.0.1 are not yet supported by SDFiles.
My suggestion is, wait until it's supported. Also, don't just update, update, update. Not everything works on New Firmwares.

**Comment by SaviorZeus** [comment]
@shchmue Yea thats the thing i did everything all files was updated lockpick.nro was on the latest it was in the switch folder i was on a supported firmware 6.2 i was using atmosphere 8.3 i print the  Fuse info & Tsec then when i load back into homebrew & click lockpick it will load for a quick sec then crash everytime . EveryOther homebrew application works perfectly fine no crashes so its like what the hell

**Comment by SaviorZeus** [comment]
@CVFireDragon Yea i know i figured that but even if i was on 6.2 it still does the same thing & i followed everyting in this guy video still crashes https://youtu.be/FjqUvJqvGLQ but im gonna change the Sd card downgrade back to 6.2 then see what happens

**Comment by SaviorZeus** [comment]
@CVFireDragon @shchmue i switch my sd card and it worked thanks for Helping guys i Appreciate it.
