### ISSUE TITLE
Lockpick error (Get Tegra keys... Failed) with the newest system 7.0.1

### ISSUE THREAD

**Issue by piooop** [shchmue/Lockpick#13]
my sd card isn't corrupted and i am using hekate - CTCaer mod v4.9.1

**Comment by shchmue** [comment]
what's in your /backup folder on SD

**Comment by piooop** [comment]
fuses.bin and tsec_keys.bin

**Comment by piooop** [comment]
a folder called 87b218a5

**Comment by shchmue** [comment]
do you have a dumps folder inside that with files inside? if so what are they named

**Comment by piooop** [comment]
yes and they are called fuses.bin and tsec_keys.bin

**Comment by shchmue** [comment]
try deleting the /dumps subfolder and re-dumping the keys with hekate

**Comment by piooop** [comment]
it didnt work

**Comment by shchmue** [comment]
okay. what CFW + CFW version are you running, and what is the whole output of Lockpick?

**Comment by piooop** [comment]
how do i look that information

**Comment by shchmue** [comment]
where did you get your CFW files from, what payload do you use

**Comment by piooop** [comment]
i downloade all from here

**Comment by shchmue** [comment]
this repo does not host and CFW files. do you use Atmosphere, Kosmos, ReiNX, SX OS?

**Comment by piooop** [comment]
sorry from here https://mega.nz/#!qKhl1SLb!oRIB-YbzfOHpeayl7XhMahgwiEdEPPvOgMWt89qlLSE

**Comment by shchmue** [comment]
did you get that from a video guide or something? that looks like an outdated version of Kosmos. it contains an outdated version of Lockpick. so at the very least replace Lockpick.nro in the /switch/ folder with the latest release https://github.com/shchmue/Lockpick/releases but i'd also recommend replacing those files with the latest kosmos, including an up-to-date hekate

**Comment by piooop** [comment]
yes this is the video is in spanish https://www.youtube.com/watch?v=Zwdzj2E0G0g

**Comment by shchmue** [comment]
i should note you'll need to run Lockpick_RCM instead to get the 7.0 keys https://github.com/shchmue/Lockpick_RCM/releases

**Comment by kotapo** [comment]
I have the same problem. I already tried several of the things you mentioned here, including the latest updates of lockpick rcm and lockpick.nro.
I'm still getting "get tegra keys... Failed" and I do not have a backup folder. Please help.

**Comment by shchmue** [comment]
i might need to change the wording in the program or something, but that doesn't matter as long as you already ran lockpick_rcm
