### ISSUE TITLE
can't retrieve key with 1.6.3 -> okay with 1.3.0

### ISSUE THREAD

**Issue by kouik03** [shchmue/Lockpick#17]
Using version 1.6.3 fails with this message  :

can't write to sd:/switch

using version 1.3.0 without any further change, looks to be 100% fine, with the keys being produced in the switch folder as expected.

happy to reply questions/test if needed ;)

switch v 6.1.0 , versions downloaded from github directly

**Comment by shchmue** [comment]
wrong project, i'm gonna close this on here but keep an eye on this issue for the same problem: https://github.com/shchmue/Lockpick_RCM/issues/12
