### ISSUE TITLE
12.0 support

### ISSUE THREAD

**Issue by SacredPKMN** [shchmue/Lockpick#20]
plz

**Comment by shchmue** [comment]
this program can’t do much in general. you should use Lockpick_RCM. does the program itself not work in 12.0? what happens when you run it

**Comment by bblyse001** [comment]
i have the same problem , the program just doesnt work and the hbmenu crashes everytime i try to boot lockpick
and Lockpick_RCM is not an option since im on a NS Patched (mariko)

:)

**Comment by shchmue** [comment]
flash spacecraft-nx on your chip and run lockpick-rcm. this program is never going to be useful on mariko as far as anyone can predict. even the derivation method it uses is completely obsolete on mariko.
