### ISSUE TITLE
Doesn't work, fail to dump the keys.

### ISSUE THREAD

**Issue by jlozes** [shchmue/Lockpick#4]
I encountered a problem to make the homebrew work. My file "fuses.bin" and "tsec_keys.bin" have been dumped with Hekate 4.2, I've also try to dump the Bis keys on my SD with the Biskeydump V7 payload and the homebrew always say that it has failed to extract the keys and ask to reboot the console and to try again.

I'm on 6.1.0 with auto-RCM and burned Efuses are equal to the 4.0.1 firmware, my SD is formated to EXFAT, I have never installed the 6.2.0 firmware. I've tried with Atmosphere, Kosmos and SX OS, same result on the three CFWs. On Atmosphere the debug option is activated, on Kosmos not and on SX OS it's not possible to configure this feature.

I've tried to copy the files to the root of the "Backup" folder, to "Backup/Dumps", to "Backup/console_id/Dump", to the root of the SD and to "switch/Lockpick". I don't know what to do to make it work now, that's why I ask to you what could I forget to try.

Note: Kezplez-NX work with this configuration, maybe it's important to precise it.

Thanks.

**Comment by shchmue** [comment]
That's the titlekeys that are failing to dump, that means you've never installed any games or played any cartridges on that switch before. In the next version, there will be a check for this and a better error message, but you should already have your regular key file called prod.keys in the /switch folder on SD. In your case, it should contain 112 keys.

**Comment by jlozes** [comment]
My bad, I hadn't seen the files on my "switch" folder, I haven't think to check it. Effectivly, the files are there, sory for that, I close the issue.
