### ISSUE TITLE
Failed to get key_06

### ISSUE THREAD

**Issue by Ryuuhou** [shchmue/Lockpick#7]
I have followed the guide, dumped fuses/tsec and ran Lockpick multiple times, no errors, 113 keys found but no _06 keys. I am on 6.2.0 using latest Atmosphere, I double checked. Not using any emunand.

EDIT: Does lockpick check version number using BOOT0/1? I did a NAND restore to 4.1.0 and then back to 6.2.0 but I may have possibly forgot to restore the BOOT0/1 of the 6.2.0 backup, I may not have noticed since my switch is bootable.

EDIT2: I used ChourjourNX 6.2.0->6.2.0 to restore boot files in case, no change in results, still no master key6.

**Comment by shchmue** [comment]
Are you using Hekate 4.6 to dump TSEC?

**Comment by Ryuuhou** [comment]
No, I used 4.5, I didn't bother to update since the guide said 4.5+. Thought that included 4.5. I will try with 4.6 later.

**Comment by shchmue** [comment]
Whoops you're right. You might need to delete your /backup/<nand serial>/dumps folder and try again, come to think of it a few people have had to. And your Switch wouldn't boot at all if you had boot0 on a different version than the rest.

**Comment by Ryuuhou** [comment]
That did the trick, thanks.

**Comment by headhunteerr** [comment]
Hello,

I have the same problem, not having the _06 keys in my file..
I am on SXOS 6.2.0 emuNAND and 4.1.0 sysNAND. Do I need to update the sysNAND in order to have those keys?

Thank you =)

**Comment by shchmue** [comment]
yeah, if your sysnand isn't on 6.2.0, hekate can't get the tsec_root_key it needs to get master_key_06 and derive the rest.
